name: Extracting Features From New Instances

# Sets up a trigger for the action.
on: 
  workflow_call:
  #push: # On a push to the directory in the specified path.
   # paths:
    #  - Resources/instances/*.col

# Assigns the jobs that are to be triggered.
jobs:
  extracting: # Name of the job.
    runs-on: ubuntu-latest # Defines a base image.
    
    # Defines the steps of the job.
    steps: 
    - name: Checkout repository # Fetches code from the repo onto a virtual machine for execution.
      uses: actions/checkout@v3 # checkout@v3 is an official action maintained by github.
      with: 
        python-version: '3.x'

    - name: Install dependencies 
      run: pip install numpy # Installs numpy as its needed for the action.

    - name: Extract features
      run: python feature_extractor.py # Runs the feature extractor 
      working-directory: src/ # Using the src/ directory as the working directory.

    # Commit and push and changes made using this action to the repo.
    - name: Commit and Push Changes 
      if: success() # Only if the previous step succeeded, this should be executed.
      # defines some credential and executes the commands for commiting and pushing
      run: |
        git config --global user.name 'github-actions' 
        git config --global user..email 'github-actions@github.com'
        git add Resources
        git commit -m "Updated InstanceFeatures.csv"
        git push
